# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models

def transfer_institutions(apps, schema_editor):
    Institution = apps.get_model("courses", "Institution")
    Course = apps.get_model("courses", "Course")
    all_institutions = set()
    for course in Course.objects.all():
        all_institutions.add(course.institution)
    for institution in all_institutions:
        apply_institution = Institution(name = institution)
        apply_institution.save()
    for course in Course.objects.all():
        for institution_ob in Institution.objects.all():
            Course.objects.filter(institution = institution_ob.name).update(institution_id = institution_ob)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20190911_1837'),
    ]

    operations = [
        migrations.RunPython(transfer_institutions),
        migrations.RemoveField(
            model_name='course',
            name='institution',
        ),
    ]


