# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-09-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models

def rename(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    for course in Course.objects.all():
        course(institution = institution_id)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_transfer_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='institution', to='courses.Institution'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='course',
            name='institution_id',
        ),
    ]